import crypto from 'node:crypto';
import {
    type LanguageModelV2,
    type LanguageModelV2CallOptions,
    type LanguageModelV2StreamPart,
    type LanguageModelV2FinishReason,
    type LanguageModelV2TextPart,
    type LanguageModelV2ToolCallPart,
} from '@ai-sdk/provider';
import { resolveConfig, type OpenCodeProviderOptions, ConfigManager } from './config';
import { A2AClient } from './a2a-client';
import { 
    mapPromptToA2AJsonRpcRequest, 
    A2AStreamMapper, 
    buildConfirmationRequest,
    type MapPromptOptions, 
    type ExtendedFinishPart
} from './utils/mapper';
import { parseA2AStream } from './utils/stream';
import type { A2AJsonRpcRequest, A2AConfig, Tool } from './schemas';
import { type SessionStore, InMemorySessionStore, type A2ASession } from './session';
import { isQuotaError, getNextFallbackModel, resolveFallbackConfig, type FallbackConfig } from './fallback';
import { DefaultMultiAgentRouter } from './router';
import { Logger } from './utils/logger';


/** チャンクが届かない場合のウォッチドッグタイムアウト (ms)のデフォルト値、10分 */
const DEFAULT_CHUNK_TIMEOUT_MS = 10 * 60 * 1000;
/** contextToolFrequency の最大キャッシュ件数 */
const MAX_CONTEXT_CACHE = 100;

function anySignal(signals: (AbortSignal | undefined)[]): AbortSignal {
    const controller = new AbortController();
    const handlers: Array<{ signal: AbortSignal; handler: () => void }> = [];

    const cleanup = () => {
        for (const { signal, handler } of handlers) {
            signal.removeEventListener('abort', handler);
        }
        handlers.length = 0;
    };

    for (const signal of signals) {
        if (!signal) continue;
        if (signal.aborted) {
            cleanup();
            controller.abort(signal.reason);
            return signal;
        }
        const handler = () => {
            cleanup();
            controller.abort(signal.reason);
        };
        signal.addEventListener('abort', handler, { once: true });
        handlers.push({ signal, handler });
    }

    // controller 自体が外部からアボートされた場合もクリーンアップする
    controller.signal.addEventListener('abort', cleanup, { once: true });

    return controller.signal;
}

function isAutoConfirmTarget(part: ExtendedFinishPart | undefined, textPartCounter: number = 0): boolean {
    if (!part) return false;
    const hasSpoken = textPartCounter > 0;
    if (part.coderAgentKind === 'tool-call-confirmation') {
        return part.inputRequired === true && part.hasExposedTools !== true;
    }
    const isInternalRecall = part.coderAgentKind === 'internal-tool-call';
    const isBackgroundAgent = part.coderAgentKind === 'codebase_investigator' || part.coderAgentKind === 'generalist';
    if (isBackgroundAgent) {
        return part.inputRequired === true && part.hasExposedTools !== true;
    }
    if (isInternalRecall) {
        return !hasSpoken && part.inputRequired === true && part.hasExposedTools !== true;
    }
    return false;
}

async function* withChunkTimeout<T>(iterable: AsyncIterable<T>, timeoutMs: number): AsyncIterable<T> {
    const iterator = iterable[Symbol.asyncIterator]();
    try {
        while (true) {
            let timeoutHandle: ReturnType<typeof setTimeout> | undefined;
            const timeoutPromise = new Promise<never>((_, reject) => {
                timeoutHandle = setTimeout(() => {
                    reject(new Error(`Chunk timeout after ${timeoutMs}ms. The upstream agent may be stuck.`));
                }, timeoutMs);
            });
            try {
                const nextPromise = iterator.next();
                const result = await Promise.race([nextPromise, timeoutPromise]);
                if (result.done) break;
                yield result.value;
            } finally {
                clearTimeout(timeoutHandle);
            }
        }
    } finally {
        if (typeof iterator.return === 'function') {
            try {
                await iterator.return();
            } catch (e) {
                // Ignore errors during iterator closure
            }
        }
    }
}

export class OpenCodeGeminiA2AProvider implements LanguageModelV2 {
    private options: OpenCodeProviderOptions;
    private client: A2AClient | undefined;
    private sessionStore: SessionStore;
    private contextToolFrequency: Map<string, Record<string, number>> = new Map();
    public readonly modelId: string;
    public readonly modelID: string;
    public readonly specificationVersion = 'v2';
    public readonly provider = 'opencode-geminicli-a2a';
    public readonly providerId = 'opencode-geminicli-a2a';
    public readonly providerID = 'opencode-geminicli-a2a';
    public readonly id = 'opencode-geminicli-a2a';
    public readonly name = 'Gemini CLI (A2A)';
    public readonly supportedUrls: Record<string, RegExp[]> = {};

    private unregisterConfigWatcher?: () => void;
    private autoGeneratedSessionId?: string;

    constructor(modelId: string, options: OpenCodeProviderOptions = {}) {
        this.modelId = modelId;
        this.modelID = modelId;
        this.options = options;
        this.sessionStore = options.sessionStore || new InMemorySessionStore();

        if (options.hotReload) {
            this.unregisterConfigWatcher = ConfigManager.getInstance().onChange(() => {
                Logger.info(`[Provider] Hot-reloading configuration for model ${this.modelId}`);
                this.client = undefined; // Force re-creation on next use
            });
        }
    }

    public dispose() {
        if (this.unregisterConfigWatcher) {
            this.unregisterConfigWatcher();
        }
    }

    private async ensureClient(): Promise<void> {
        if (this.client) return;
        const config = resolveConfig(this.options);
        
        // マルチエージェント対応: modelId に対応するエンドポイントがあればそれを使う
        const agents = config.agents;
        if (agents && agents.length > 0) {
            const router = new DefaultMultiAgentRouter(agents);
            const resolved = router.resolve(this.modelId);
            if (resolved) {
                const agentConfig = {
                    ...config,
                    host: resolved.endpoint.host,
                    port: resolved.endpoint.port,
                    protocol: resolved.endpoint.protocol || config.protocol,
                    token: resolved.endpoint.token || config.token,
                };
                this.client = new A2AClient(agentConfig);
                return;
            }
        }
        
        this.client = new A2AClient(config);
    }

    private get resolvedOptions() {
        return resolveConfig(this.options);
    }

<<<<<<< HEAD
    async doStream(options: LanguageModelV2CallOptions): Promise<{
        stream: ReadableStream<LanguageModelV2StreamPart>;
        request?: { body?: string };
        response?: { headers?: Record<string, string> };
    }> {
        await this.ensureClient();
        
        const sessionId = options.headers?.['x-opencode-session-id'] || options.headers?.['x-session-id'] || (options as any).providerMetadata?.opencode?.sessionId;
        let session = sessionId ? await this.sessionStore.get(sessionId) : undefined;
        const resetContext = (options as any).providerMetadata?.opencode?.resetContext || (options as any).providerOptions?.opencode?.resetContext;
        
        if (session && resetContext) {
            session.contextId = undefined;
            session.taskId = undefined;
            if (sessionId && sessionId !== 'undefined') {
                await this.sessionStore.update(sessionId, session);
=======
        // Sticky fallback check
        const opencodeMetadata = options.providerMetadata?.opencode;
        let sessionId = opencodeMetadata?.sessionId ? String(opencodeMetadata.sessionId).trim() : undefined;
        if (sessionId && !(options as any)._isFallbackInstance) {
            const session = await this.sessionStore.get(sessionId);
            if (session?.failedModelIds?.includes(this.modelId)) {
                // The originally requested model failed previously in this session.
                // We should preemptively trigger the fallback logic instead of waiting for a quota error.
                Logger.info(`[opencode-geminicli-a2a] Preemptively falling back from ${this.modelId} as it failed previously in this session.`);
                const fakeError = new Error("Sticky Quota Fallback");
                (fakeError as any).status = 429;
                return this._attemptFallback(options, fakeError);
            }
        }

        let result: LanguageModelV1StreamResult;
        try {
            result = await this._doStreamInternal(options);
        } catch (error) {
            if (this.fallbackConfig && isQuotaError(error, this.fallbackConfig)) {
                return this._attemptFallback(options, error);
>>>>>>> 7a73656 (fix(provider): resolve TypeError chunk.delta.length during loop interrupt)
            }
        }
        
        if (!session) {
            session = { 
                contextId: undefined, 
                taskId: undefined, 
                processedMessagesCount: 0,
                toolCallFrequency: {},
                fallbackCounters: {},
            };
            if (sessionId && sessionId !== 'undefined') {
                await this.sessionStore.update(sessionId, session);
            }
        }

        const idempotencyKey = options.headers?.['idempotency-key'] || 
                               options.headers?.['x-opencode-idempotency-key'] || 
                               (options as any).providerMetadata?.opencode?.idempotencyKey || 
                               crypto.randomUUID();

        const baseConfig = this.resolvedOptions;

        let agentOptions: any = undefined;
        if (baseConfig.agents) {
            const router = new DefaultMultiAgentRouter(baseConfig.agents);
            const resolved = router.resolve(this.modelId);
            if (resolved && resolved.config && resolved.config.options) {
                agentOptions = resolved.config.options;
            }
        }

        const resolvedBaseConfig = {
            ...baseConfig,
            ...(agentOptions || {}),
        };

        const generationConfig: Record<string, any> = {
            ...(baseConfig.generationConfig || {}),
            ...(agentOptions?.generationConfig || {}),
            ...(options as any).generationConfig || {},
        };

        if ((options as any).temperature !== undefined) generationConfig.temperature = (options as any).temperature;
        if ((options as any).topP !== undefined) generationConfig.topP = (options as any).topP;
        if ((options as any).topK !== undefined) generationConfig.topK = (options as any).topK;
        if ((options as any).maxTokens !== undefined) generationConfig.maxOutputTokens = (options as any).maxTokens;
        if ((options as any).stopSequences !== undefined) generationConfig.stopSequences = (options as any).stopSequences;

        const mapOptions: MapPromptOptions = {
            tools: (options as any).mode?.type === 'regular' ? (options as any).mode.tools : ((options as any).tools || undefined),
            toolMapping: resolvedBaseConfig.toolMapping,
            internalTools: resolvedBaseConfig.internalTools,
            contextId: session.contextId,
            taskId: session.taskId,
            processedMessagesCount: session.processedMessagesCount,
            modelId: this.modelId,
            generationConfig: Object.keys(generationConfig).length > 0 ? generationConfig : undefined,
        };

        const initialRequestData = mapPromptToA2AJsonRpcRequest(options.prompt, mapOptions);
        const serializedRequestForTest = JSON.stringify(initialRequestData);
        
        const toolsArr = (options as any).mode?.type === 'regular' ? (options as any).mode.tools : ((options as any).tools || []);
        const clientTools = toolsArr 
            ? toolsArr.map((t: any) => t.function?.name || t.name || t.type).filter((n: any): n is string => !!n) 
            : [];
        
        // session.processedMessagesCount 以降に 'user' ロールのメッセージがあるかを確認して新規ユーザーターンと判定する
        const isNewUserTurn = options.prompt.slice(session.processedMessagesCount || 0).some(m => m.role === 'user');

        const startTime = Date.now();
        const isTestEnv = process.env.NODE_ENV === 'test';
        const TIMEOUT_MS = isTestEnv ? 3000 : 300000;
        
        const timeoutAbortController = new AbortController();
        const timeoutHandle = setTimeout(() => {
            timeoutAbortController.abort('EXECUTION_TIMEOUT');
        }, TIMEOUT_MS);

        const combinedAbortController = new AbortController();
        if (options.abortSignal) {
            options.abortSignal.addEventListener('abort', () => combinedAbortController.abort(options.abortSignal?.reason), { once: true });
        }
        timeoutAbortController.signal.addEventListener('abort', () => combinedAbortController.abort(timeoutAbortController.signal.reason), { once: true });

        let responseStream: ReadableStream<Uint8Array>;
        let headers: Record<string, string>;
        let lastFinishPart: ExtendedFinishPart | undefined = undefined;

        try {
            const firstChatResponse = await this.client!.chatStream({ 
                request: initialRequestData, 
                abortSignal: combinedAbortController.signal,
                idempotencyKey
            });
            responseStream = firstChatResponse.stream;
            headers = firstChatResponse.headers;
        } catch (error) {
            const currentFallbackConfig = resolveFallbackConfig(this.options.fallback);
            if (isQuotaError(error, currentFallbackConfig) && currentFallbackConfig) {
                const counters = (session as any).fallbackCounters || {};
                const totalRetries = Object.values(counters).reduce((sum: number, val: any) => sum + (val as number), 0);
                
                if (totalRetries < (currentFallbackConfig.maxRetries ?? 3)) {
                    const nextModel = getNextFallbackModel(this.modelId, currentFallbackConfig);
                    if (nextModel) {
                        Logger.warn(`Quota exceeded for ${this.modelId}. Falling back to ${nextModel}. Total retries: ${totalRetries + 1}`);
                        counters[this.modelId] = (counters[this.modelId] || 0) + 1;
                        (session as any).fallbackCounters = counters;
                        if (sessionId && sessionId !== 'undefined') await this.sessionStore.update(sessionId, { fallbackCounters: counters });
                        
                        const provider = new OpenCodeGeminiA2AProvider(nextModel, {
                            ...this.options,
                            sessionStore: this.sessionStore
                        });
                        clearTimeout(timeoutHandle);
                        return provider.doStream({
                            ...options,
                            headers: {
                                ...options.headers,
                                'idempotency-key': idempotencyKey
                            }
                        });
                    }
                } else {
                    Logger.error(`Max fallback retries reached (${totalRetries}). Giving up.`);
                }
            }
            clearTimeout(timeoutHandle);
            throw error;
        }

        const frequencyContextId = session.contextId;
        if (isNewUserTurn && sessionId) {
            session.toolCallFrequency = {};
            if (frequencyContextId) {
                this.contextToolFrequency.delete(frequencyContextId);
            }
        }

        const instanceFreq = frequencyContextId
            ? this.contextToolFrequency.get(frequencyContextId)
            : undefined;
            
        const mapper = new A2AStreamMapper({
            toolMapping: resolvedBaseConfig.toolMapping,
            internalTools: resolvedBaseConfig.internalTools,
            clientTools: clientTools as string[],
            initialToolCallFrequency: instanceFreq ?? session.toolCallFrequency,
            maxToolCallFrequency: resolvedBaseConfig.maxToolCallFrequency ?? this.options?.maxToolCallFrequency,
        });

        const stream = new ReadableStream<LanguageModelV2StreamPart>({
            start: (controller) => {
                let textPartCounter = 0;
                let reasoningPartCounter = 0;
                let activeTextId: string | undefined;
                let activeReasoningId: string | undefined;
                let isControllerClosed = false;

<<<<<<< HEAD
                const safeEnqueue = (part: LanguageModelV2StreamPart) => {
                    if (!isControllerClosed) {
                        try {
                            controller.enqueue(part);
                        } catch (e) {
                            Logger.warn('[Provider] controller closed prematurely');
                            isControllerClosed = true;
=======
                        if (value?.type === 'stream-start') {
                            if (streamStartEmitted) continue;
                            streamStartEmitted = true;
                        }

                        controller.enqueue(value);
                        return;
                    } catch (error) {
                        if (!fallbackAttempted && isQuotaError(error, fallbackConfig)) {
                            fallbackAttempted = true;
                            Logger.info(`[opencode-geminicli-a2a] Stream error detected. Attempting fallback...`);
                            try {
                                const fallbackResult = await self._attemptFallback(options, error);
                                currentReader.releaseLock();
                                currentReader = fallbackResult.stream.getReader();
                                continue;
                            } catch (fallbackError) {
                                controller.error(fallbackError);
                                return;
                            }
                        } else {
                            controller.error(error);
                            return;
>>>>>>> 7a73656 (fix(provider): resolve TypeError chunk.delta.length during loop interrupt)
                        }
                    }
                };
                const safeError = (err: any) => {
                    if (!isControllerClosed) {
                        controller.error(err);
                        isControllerClosed = true;
                    }
                };
                const safeClose = () => {
                    if (!isControllerClosed) {
                        controller.close();
                        isControllerClosed = true;
                    }
                };

                const closeText = () => {
                    if (activeTextId !== undefined) {
                        safeEnqueue({ type: 'text-end', id: activeTextId } as any);
                        activeTextId = undefined;
                    }
                };
                const closeReasoning = () => {
                    if (activeReasoningId !== undefined) {
                        safeEnqueue({ type: 'reasoning-end', id: activeReasoningId } as any);
                        activeReasoningId = undefined;
                    }
                };
                const enqueueText = (delta: string) => {
                    if (!delta) return;
                    if (activeTextId === undefined) {
                        activeTextId = `text-${textPartCounter++}`;
                        safeEnqueue({ type: 'text-start', id: activeTextId } as any);
                    }
                    safeEnqueue({ type: 'text-delta', id: activeTextId, delta } as any);
                };

                (async () => {
                    try {
                        let currentRequest = initialRequestData;
                        let autoConfirmCount = 0;
                        let toolCallConfirmCount = 0;
                        const MAX_AUTO_CONFIRM = resolvedBaseConfig.maxAutoConfirm ?? this.options?.maxAutoConfirm ?? 50;
                        const MAX_TOOL_CONFIRM = 1;

                        let firstResponse: any = { stream: responseStream, headers: headers || {} };

                        const loop = async () => {
                            while (true) {
                                if (Date.now() - startTime > TIMEOUT_MS) {
                                    throw new Error('EXECUTION_TIMEOUT');
                                }

<<<<<<< HEAD
                                let hasFinishedInThisTurn = false;
                                const combinedSignal = options.abortSignal 
                                    ? anySignal([options.abortSignal, timeoutAbortController.signal])
                                    : timeoutAbortController.signal;

                                const response = firstResponse || await this.client!.chatStream({ 
                                    request: currentRequest, 
                                    abortSignal: combinedSignal,
                                    idempotencyKey
                                });
                                firstResponse = undefined;

                                mapper.startNewTurn();
                                const chunkTimeoutMs = resolvedBaseConfig.chunkTimeoutMs ?? this.options?.chunkTimeoutMs ?? DEFAULT_CHUNK_TIMEOUT_MS;
                                const chunkGenerator = withChunkTimeout(parseA2AStream(response.stream), chunkTimeoutMs);

                                for await (const chunk of chunkGenerator) {
                                    if ('result' in chunk && chunk.result) {
                                        const parts = mapper.mapResult(chunk.result);
                                        for (const part of parts) {
                                            switch (part.type) {
                                                case 'text-delta': {
                                                    enqueueText((part as any).textDelta || (part as any).delta);
                                                    break;
                                                }
                                                case 'reasoning-delta': {
                                                    closeText();
                                                    if (activeReasoningId === undefined) {
                                                        activeReasoningId = `reasoning-${reasoningPartCounter++}`;
                                                        safeEnqueue({ type: 'reasoning-start', id: activeReasoningId } as any);
                                                    }
                                                    safeEnqueue(part as any);
                                                    break;
                                                }
                                                case 'tool-call': {
                                                    closeText();
                                                    closeReasoning();
                                                    safeEnqueue({
                                                        type: 'tool-call',
                                                        toolCallId: part.toolCallId,
                                                        toolName: part.toolName,
                                                        args: typeof (part as any).args === 'string' ? (part as any).args : JSON.stringify((part as any).args),
                                                    } as any);
                                                    break;
                                                }
                                                case 'finish': {
                                                    hasFinishedInThisTurn = true;
                                                    lastFinishPart = part as ExtendedFinishPart;
                                                    if (!isAutoConfirmTarget(lastFinishPart, textPartCounter)) {
                                                        closeText();
                                                        closeReasoning();
                                                        const unifiedFinishReason = (lastFinishPart.finishReason === 'unknown' ? 'stop' : lastFinishPart.finishReason);
                                                        safeEnqueue({
                                                            type: 'finish',
                                                            finishReason: unifiedFinishReason as LanguageModelV2FinishReason,
                                                            usage: {
                                                                inputTokens: { total: lastFinishPart.usage.promptTokens },
                                                                outputTokens: { total: lastFinishPart.usage.completionTokens },
                                                            },
                                                        } as any);
                                                    }
                                                    break;
                                                }
                                                default:
                                                    safeEnqueue(part as any);
                                                    break;
=======
        Logger.info(`[opencode-geminicli-a2a] Falling back from ${this.modelId} to ${nextModelId} (level ${fallbackCount + 1})`);

        // Save fallback model to session for sticky fallback on subsequent turns
        const opencodeMetadata = callOptions.providerMetadata?.opencode;
        const sessionId = opencodeMetadata?.sessionId ? String(opencodeMetadata.sessionId).trim() : undefined;
        if (sessionId) {
            const session = await this.sessionStore.get(sessionId) || {};
            const failedIds = session.failedModelIds || [];
            if (!failedIds.includes(this.modelId)) {
                failedIds.push(this.modelId);
                await this.sessionStore.update(sessionId, { failedModelIds: failedIds });
            }
        }

        const fallbackProvider = new OpenCodeGeminiA2AProvider(nextModelId, {
            ...this.options,
            hotReload: false, // フォールバックインスタンスはホットリロードを監視しない
        });
        return fallbackProvider.doStream({
            ...callOptions,
            _fallbackCount: fallbackCount + 1,
            _isFallbackInstance: true
        } as any);
    }

    private async _doStreamInternal(options: LanguageModelV1CallOptions) {
        let sessionId: string | undefined = undefined;
        const opencodeMetadata = options.providerMetadata?.opencode;
        if (opencodeMetadata?.sessionId) sessionId = String(opencodeMetadata.sessionId).trim();
        if (!sessionId) {
            if (!this.autoGeneratedSessionId) {
                this.autoGeneratedSessionId = `cli-session-auto-${crypto.randomUUID()}`;
                Logger.debug(`[Provider] Generated stable auto-session ID for instance: ${this.autoGeneratedSessionId}`);
            }
            sessionId = this.autoGeneratedSessionId;
        }

        const session = await this.sessionStore.get(sessionId) || {};
        if (!session.fallbackCounters) session.fallbackCounters = {};
        if (!session.dynamicToolMapping) session.dynamicToolMapping = {};
        if (opencodeMetadata?.resetContext === true && sessionId) {
            await this.sessionStore.resetSession(sessionId);
            delete session.contextId;
            delete session.taskId;
            delete session.lastFinishReason;
            delete session.inputRequired;
            delete session.rawState;
            session.fallbackCounters = {};
            session.dynamicToolMapping = {};
        }

        const request = this.createA2ARequest(options, session);
        const idempotencyKey = (options.providerMetadata?.opencode?.idempotencyKey as string) || undefined;

        let responseStream;
        let headers;
        try {
            const response = await this.client!.chatStream({ request, idempotencyKey, abortSignal: options.abortSignal });
            responseStream = response.stream;
            headers = response.headers;
        } catch (error) {
            if (sessionId) await this.sessionStore.update(sessionId, { lastFinishReason: undefined });
            throw error;
        }

        const rawToolsInput = options.mode?.type === 'regular' ? options.mode.tools : (options as any).tools;
        const clientTools = Array.isArray(rawToolsInput)
            ? rawToolsInput.map((t: any) => t.name || t.id || t.function?.name || t.type).filter(Boolean) as string[]
            : (rawToolsInput && typeof rawToolsInput === 'object' ? Object.keys(rawToolsInput) : undefined);

        // 優先順位: プロバイダーインスタンスレベル(contextIdキー) > セッションストア
        const frequencyContextId = session.contextId;
        const instanceFreq = frequencyContextId
            ? this.contextToolFrequency.get(frequencyContextId)
            : undefined;
        const mapper = new A2AStreamMapper({
            toolMapping: this.resolvedOptions?.toolMapping,
            internalTools: this.resolvedOptions?.internalTools,
            clientTools,
            // インスタンスレベルの頻度を優先、なければセッションストアのものを使う
            initialToolCallFrequency: instanceFreq ?? session.toolCallFrequency,
        });
        let textPartCounter = 0;
        let reasoningPartCounter = 0;
        let activeTextId: string | undefined;

        const stream = new ReadableStream<any>({
            start: async (controller) => {
                let currentRequest = request;
                let autoConfirmCount = 0;
                let toolCallConfirmCount = 0;
                const MAX_AUTO_CONFIRM = 50;          // internal-tool-call 用 (codebase_investigator 等の長時間実行エージェント対応のため拡大)
                const MAX_TOOL_CONFIRM = 1;           // tool-call-confirmation 用 (invalid ツールのリトライループ防止)

                let firstResponse: any = { stream: responseStream, headers: headers || {} };
                let lastFinishPart: ExtendedFinishPart | undefined;

                try {
                    controller.enqueue({ type: 'stream-start' });

                    while (autoConfirmCount < MAX_AUTO_CONFIRM) {
                        let hasFinished = false;
                        let response = firstResponse || await this.client!.chatStream({ request: currentRequest, abortSignal: options.abortSignal });
                        firstResponse = undefined;

                        mapper.startNewTurn();
                        // ウォッチドッグでラップ: チャンクが CHUNK_TIMEOUT_MS 来なければタイムアウトエラー
                        const chunkTimeoutMs = this.options?.chunkTimeoutMs ?? DEFAULT_CHUNK_TIMEOUT_MS;
                        const chunkGenerator = withChunkTimeout(
                            parseA2AStream(response.stream),
                            chunkTimeoutMs,
                        );

                        for await (const chunk of chunkGenerator) {
                            if ('result' in chunk && chunk.result) {
                                const parts = mapper.mapResult(chunk.result);
                                for (const part of parts) {
                                    switch (part.type) {
                                        case 'text-delta': {
                                            if (activeTextId === undefined) {
                                                activeTextId = `text-${textPartCounter++}`;
                                                controller.enqueue({ type: 'text-start', id: activeTextId });
>>>>>>> 7a73656 (fix(provider): resolve TypeError chunk.delta.length during loop interrupt)
                                            }
                                        }
                                    } else if ('error' in chunk && chunk.error) {
                                        throw new Error(`A2A JSON-RPC Error: [${chunk.error.code}] ${chunk.error.message}`);
                                    }
                                }

                                if (!hasFinishedInThisTurn) {
                                    throw new Error('A2A stream disconnected before sending final status-update.');
                                }

<<<<<<< HEAD
                                if (lastFinishPart?.shouldInterruptLoop) {
                                    Logger.warn(`[auto-confirm] Loop detected. Force terminating.`);
                                    closeReasoning();
                                    enqueueText(`\n\n[opencode-geminicli-a2a] ⚠️ エージェントが同一の内部ツールを何度も呼び出したため、ループを強制中断しました。\n`);
                                    closeText();
                                    safeEnqueue({
                                        type: 'finish',
                                        finishReason: 'stop',
                                        usage: {
                                            inputTokens: { total: lastFinishPart.usage.promptTokens || 0 },
                                            outputTokens: { total: lastFinishPart.usage.completionTokens || 0 },
=======
                        if (isAutoConfirmTarget(lastFinishPart) && mapper.taskId) {
                            if (lastFinishPart?.shouldInterruptLoop) {
                                Logger.warn(`[auto-confirm] 内部ルールの重複検知によりループを強制終了.`);
                                const interruptId = `text-${textPartCounter++}`;
                                controller.enqueue({ type: 'text-start', id: interruptId });
                                controller.enqueue({
                                    type: 'text-delta',
                                    id: interruptId,
                                    delta: `\n\n[opencode-geminicli-a2a] ⚠️ エージェントが同一の内部ツールを何度も呼び出したため、ループを強制中断しました。\n`
                                });
                                controller.enqueue({ type: 'text-end', id: interruptId });
                                controller.enqueue({
                                    type: 'finish',
                                    finishReason: 'stop',
                                    usage: {
                                        promptTokens: lastFinishPart?.usage?.inputTokens?.total || 0,
                                        completionTokens: lastFinishPart?.usage?.outputTokens?.total || 0,
                                    },
                                    finishReasonV3: { unified: 'stop' as any, raw: 'internal-loop-detected' },
                                } as any);
                                break;
                            }

                            const isToolConfirm = lastFinishPart?.coderAgentKind === 'tool-call-confirmation';

                            if (isToolConfirm) {
                                toolCallConfirmCount++;
                                if (toolCallConfirmCount > MAX_TOOL_CONFIRM) {
                                    // invalid なツール（read_file 等）によるループを検知。
                                    // これ以上 "Proceed" を送るとループするため、finish を emit して終了する。
                                    Logger.warn(`[auto-confirm] tool-call-confirmation が ${toolCallConfirmCount} 回発生。ループの可能性があるため中断します。`);
                                    controller.enqueue({
                                        type: 'finish',
                                        finishReason: 'stop',
                                        usage: {
                                            promptTokens: lastFinishPart?.usage?.inputTokens?.total || 0,
                                            completionTokens: lastFinishPart?.usage?.outputTokens?.total || 0,
>>>>>>> 7a73656 (fix(provider): resolve TypeError chunk.delta.length during loop interrupt)
                                        },
                                    } as any);
                                    
                                    // A2Aサーバーがinput-requiredのままでハングしないよう、Cancelを送信する
                                    if (lastFinishPart.taskId) {
                                        const cancelParam = buildConfirmationRequest(lastFinishPart.taskId, this.modelId, false);
                                        this.client!.chatStream({ request: cancelParam, abortSignal: timeoutAbortController.signal }).catch((err: any) => {
                                            Logger.error(`[Provider] Failed to send loop-interrupt Cancel to A2A server:`, err);
                                        });
                                    }
                                    
                                    break;
                                }

                                const canAutoConfirm = isAutoConfirmTarget(lastFinishPart!, textPartCounter);
                                if (canAutoConfirm && lastFinishPart.taskId) {
                                    if (autoConfirmCount < MAX_AUTO_CONFIRM) {
                                        autoConfirmCount++;
                                        currentRequest = buildConfirmationRequest(
                                            lastFinishPart.taskId!,
                                            this.modelId,
                                            true
                                        );
                                        mapper.startNewTurn();
                                        continue;
                                    } else {
                                        Logger.warn(`[auto-confirm] MAX_AUTO_CONFIRM reached. Forcing stop.`);
                                        closeReasoning();
                                        if (textPartCounter === 0) {
                                            enqueueText(`\n\n[opencode-geminicli-a2a] ⚠️ エージェントが内部処理を繰り返しすぎたため、処理を中断しました。回答が生成されていません。\n`);
                                        }
                                        closeText();
                                        safeEnqueue({
                                            type: 'finish',
                                            finishReason: 'stop',
                                            usage: { inputTokens: { total: 0 }, outputTokens: { total: 0 } },
                                        } as any);
                                        break;
                                    }
                                }

<<<<<<< HEAD
                                const isToolCallConfirm = lastFinishPart.coderAgentKind === 'tool-call-confirmation' && lastFinishPart.hasExposedTools === true;
                                if (isToolCallConfirm && lastFinishPart.taskId) {
                                    if (toolCallConfirmCount < MAX_TOOL_CONFIRM) {
                                        toolCallConfirmCount++;
                                        currentRequest = buildConfirmationRequest(
                                            lastFinishPart.taskId!,
                                            this.modelId,
                                            true
                                        );
                                        mapper.startNewTurn();
                                        continue;
                                    } else {
                                        Logger.warn(`[auto-confirm] MAX_TOOL_CONFIRM reached. Forcing stop.`);
                                        closeReasoning();
                                        closeText();
                                        safeEnqueue({
                                            type: 'finish',
                                            finishReason: 'stop',
                                            usage: { inputTokens: { total: 0 }, outputTokens: { total: 0 } },
                                        } as any);
                                        break;
                                    }
                                }

                                break;
=======
                                const internalToolNames = lastFinishPart?.internalToolNames?.length ? lastFinishPart.internalToolNames.join(', ') : '';
                                const msgDelta = internalToolNames 
                                    ? `⟳ 内部ツール実行中: [${internalToolNames}] (ターン ${autoConfirmCount})\n`
                                    : `⟳ エージェントが内部処理を継続中... (ターン ${autoConfirmCount})\n`;

                                // Option 3: ループ継続中にプログレスを emit してユーザーに「生きてる」ことを伝える
                                const progressId = `reasoning-${reasoningPartCounter++}`;
                                controller.enqueue({ type: 'reasoning-start', id: progressId });
                                controller.enqueue({
                                    type: 'reasoning-delta',
                                    id: progressId,
                                    delta: msgDelta,
                                });
                                controller.enqueue({ type: 'reasoning-end', id: progressId });
>>>>>>> 7a73656 (fix(provider): resolve TypeError chunk.delta.length during loop interrupt)
                            }
                        };

                        await loop();
                    } catch (err: any) {
                        const isTimeout = err.message === 'EXECUTION_TIMEOUT' || err.name === 'AbortError' || (err as any).name === 'AbortError';
                        if (isTimeout) {
                            closeReasoning();
                            Logger.warn(`[Provider] doStream reached timeout or abort.`);
                            enqueueText(`\n\n[opencode-geminicli-a2a] ⚠️ 処理がタイムアウトしたか、中断されました。\n`);
                            closeText();
                            safeEnqueue({
                                type: 'finish',
                                finishReason: 'stop',
                                usage: {
                                    inputTokens: { total: 0 },
                                    outputTokens: { total: 0 },
                                },
                            } as any);
                        } else {
                            safeError(err);
                        }
                    } finally {
                        clearTimeout(timeoutHandle);
                        if (sessionId && sessionId !== 'undefined' && session) {
                            const updatedFreq = mapper.currentToolCallFrequency;
                            const updatedContextId = mapper.contextId || session.contextId;
                            if (updatedContextId) {
                                if (!this.contextToolFrequency.has(updatedContextId) && this.contextToolFrequency.size >= MAX_CONTEXT_CACHE) {
                                    const oldestKey = this.contextToolFrequency.keys().next().value;
                                    if (oldestKey !== undefined) this.contextToolFrequency.delete(oldestKey);
                                }
                                this.contextToolFrequency.set(updatedContextId, updatedFreq);
                            }
                            await this.sessionStore.update(sessionId, {
                                contextId: mapper.contextId || session.contextId,
                                taskId: mapper.taskId || session.taskId,
                                processedMessagesCount: options.prompt.length,
                                toolCallFrequency: updatedFreq,
                                inputRequired: lastFinishPart?.inputRequired,
                                rawState: lastFinishPart?.inputRequired ? 'input-required' : undefined,
                            });
                        }
                        safeClose();
                    }
<<<<<<< HEAD
                })();
=======

                    if (sessionId) {
                        const updatedFreq = mapper.currentToolCallFrequency;
                        // A2A contextId が確定したらプロバイダーインスタンスレベルで保存
                        // セッションIDの安定性に依存せず、contextId を安定キーとして使う
                        const updatedContextId = mapper.contextId || session.contextId;
                        if (updatedContextId) {
                            this.contextToolFrequency.set(updatedContextId, updatedFreq);
                        }
                        await this.sessionStore.update(sessionId, {
                            contextId: mapper.contextId || session.contextId,
                            taskId: mapper.taskId || session.taskId,
                            lastFinishReason: mapper.lastFinishReason || lastFinishPart?.finishReason,
                            processedMessagesCount: options.prompt.length,
                            inputRequired: lastFinishPart?.inputRequired,
                            rawState: lastFinishPart?.rawState,
                            fallbackCounters: session.fallbackCounters,
                            dynamicToolMapping: session.dynamicToolMapping,
                            toolCallFrequency: updatedFreq,
                        });
                    }

                    if (activeTextId !== undefined) controller.enqueue({ type: 'text-end', id: activeTextId });
                    controller.close();
                } catch (error) {
                    if (sessionId) await this.sessionStore.update(sessionId, { lastFinishReason: undefined });
                    controller.error(error);
                }
>>>>>>> 7a73656 (fix(provider): resolve TypeError chunk.delta.length during loop interrupt)
            },
        });

        return {
            stream,
            request: { body: serializedRequestForTest },
            response: { headers: headers! },
        };
    }

    async doGenerate(options: LanguageModelV2CallOptions): Promise<any> {
        const { stream: sdkStream, request, response } = await this.doStream(options);
        const reader = sdkStream.getReader();
        let reasoning = '';
        const toolCalls: any[] = [];
        const content: any[] = [];
        let finishReason: LanguageModelV2FinishReason = 'other';
        const usage = { promptTokens: 0, completionTokens: 0 };

        try {
            while (true) {
                const { done, value } = await reader.read();
                if (done) break;

                switch (value.type) {
                    case 'text-delta': {
                        const delta = (value as any).textDelta || (value as any).delta;
                        if (delta) {
                            if (content.length > 0 && content[content.length - 1].type === 'text') {
                                (content[content.length - 1] as any).text += delta;
                            } else {
                                content.push({ type: 'text', text: delta });
                            }
                        }
                        break;
                    }
                    case 'reasoning-delta': {
                        const delta = (value as any).delta || (value as any).reasoningDelta;
                        if (delta) {
                            reasoning += delta;
                        }
                        break;
                    }
                    case 'tool-call':
                        toolCalls.push({ 
                            toolCallId: value.toolCallId, 
                            toolName: value.toolName, 
                            args: (value as any).args as any
                        });
                        content.push({ 
                            type: 'tool-call', 
                            toolCallId: value.toolCallId, 
                            toolName: value.toolName, 
                            args: (value as any).args as any
                        });
                        break;
                    case 'finish':
                        finishReason = value.finishReason;
                        if (value.usage) {
                            usage.promptTokens = (value.usage as any).inputTokens?.total ?? (value.usage as any).promptTokens ?? 0;
                            usage.completionTokens = (value.usage as any).outputTokens?.total ?? (value.usage as any).completionTokens ?? 0;
                        }
                        break;
                }
            }
        } finally {
            reader.releaseLock();
        }

        return {
            text: content.filter(p => p.type === 'text').map(p => p.text).join(''),
            toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
            content,
            finishReason: finishReason as LanguageModelV2FinishReason,
            usage,
            response: response as any,
            request,
            warnings: [],
            reasoning: reasoning.length > 0 ? reasoning : undefined,
        };
    }
}
