# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: npm ci && npm run lint && npm run test